name: Basic CI Pipeline

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.12, 3.13]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Run tests
        run: pytest tests

  # notify:
  #   runs-on: ubuntu-latest
  #   needs: tests
  #   if: always()

  #   steps:
  #     - name: Set Slack message
  #       id: slack-message
  #       run: |
  #         if [ "${{ needs.build.result }}" == "success" ]; then
  #           echo "message=Build succeeded!" >> $GITHUB_OUTPUT
  #         else
  #           echo "message=Build failed!" >> $GITHUB_OUTPUT
  #         fi

  #     - name: Send Slack notification
  #       uses: slackapi/slack-github-action@v2
  #       with:
  #         channel-id: 'xyz'
  #         slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
  #         text: ${{ steps.slack-message.outputs.message }}

  coverage:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Run test coverage
        run: pytest --cov=src --cov-fail-under=50 tests
