name: Security scan

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Run test coverage
        run: bandit -r src
